package com.jimi.mes_standard_capacity.model;

import com.jimi.mes_standard_capacity.model.base.BaseStandardCapacity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StandardCapacity extends BaseStandardCapacity<StandardCapacity> {
	public static final StandardCapacity dao = new StandardCapacity().dao();
}
