package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseCapacity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Capacity extends BaseCapacity<Capacity> {
	public static final Capacity dao = new Capacity().dao();
}
