package com.jimi.mes_report.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("action_log", "id", ActionLog.class);
		arp.addMapping("capacity", "id", Capacity.class);
		arp.addMapping("error_log", "id", ErrorLog.class);
		arp.addMapping("order_production", "id", OrderProduction.class);
		arp.addMapping("orders", "id", Orders.class);
		arp.addMapping("status", "id", Status.class);
		arp.addMapping("time_type", "id", TimeType.class);
		arp.addMapping("workstation_production", "id", WorkstationProduction.class);
		arp.addMapping("workstation_type", "id", WorkstationType.class);
		/*arp.addMapping("workstations_orders", "id", WorkstationsOrders.class);
		arp.addMapping("workstations_use_time", "id", WorkstationsUseTime.class);*/
	}
}

