package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseOrderProduction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderProduction extends BaseOrderProduction<OrderProduction> {
	public static final OrderProduction dao = new OrderProduction().dao();
}
