package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Status extends BaseStatus<Status> {
	public static final Status dao = new Status().dao();
}
