package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseTimeType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TimeType extends BaseTimeType<TimeType> {
	public static final TimeType dao = new TimeType().dao();
}
