package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseWorkstationProduction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkstationProduction extends BaseWorkstationProduction<WorkstationProduction> {
	public static final WorkstationProduction dao = new WorkstationProduction().dao();
}
