package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseWorkstationType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkstationType extends BaseWorkstationType<WorkstationType> {
	public static final WorkstationType dao = new WorkstationType().dao();
}
