package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseWorkstationsUseTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkstationsUseTime extends BaseWorkstationsUseTime<WorkstationsUseTime> {
	public static final WorkstationsUseTime dao = new WorkstationsUseTime().dao();
}
