package com.jimi.mes_report.model;

import com.jimi.mes_report.model.base.BaseWorkstationsOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkstationsOrders extends BaseWorkstationsOrders<WorkstationsOrders> {
	public static final WorkstationsOrders dao = new WorkstationsOrders().dao();
}
