package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseActionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActionLog extends BaseActionLog<ActionLog> {
	public static final ActionLog dao = new ActionLog().dao();
}
