package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authority extends BaseAuthority<Authority> {

	public static final Authority dao = new Authority().dao();
}
