package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseDailyCompletion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DailyCompletion extends BaseDailyCompletion<DailyCompletion> {
	public static final DailyCompletion dao = new DailyCompletion().dao();
}
