package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseDashboard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dashboard extends BaseDashboard<Dashboard> {
	public static final Dashboard dao = new Dashboard().dao();
}
