package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseDashboardForCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DashboardForCustomer extends BaseDashboardForCustomer<DashboardForCustomer> {
	public static final DashboardForCustomer dao = new DashboardForCustomer().dao();
}
