package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseDataRelativeUnique;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataRelativeUnique extends BaseDataRelativeUnique<DataRelativeUnique> {

	public static final DataRelativeUnique dao = new DataRelativeUnique().dao();
}
