package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseDataRelativeSheet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataRelativeSheet extends BaseDataRelativeSheet<DataRelativeSheet> {

	public static final DataRelativeSheet dao = new DataRelativeSheet().dao();
}
