package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department().dao();
}
