package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseFaceInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FaceInformation extends BaseFaceInformation<FaceInformation> {
	public static final FaceInformation dao = new FaceInformation().dao();
}
