package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseFileType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileType extends BaseFileType<FileType> {

	public static final FileType dao = new FileType().dao();
}
