package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsAutotestResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsAutotestResult extends BaseGpsAutotestResult<GpsAutotestResult> {
	public static final GpsAutotestResult dao = new GpsAutotestResult().dao();
}
