package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsAutotestResult3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsAutotestResult3 extends BaseGpsAutotestResult3<GpsAutotestResult3> {

	public static final GpsAutotestResult3 dao = new GpsAutotestResult3().dao();
}
