package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsAutotestAntidup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsAutotestAntidup extends BaseGpsAutotestAntidup<GpsAutotestAntidup> {
	public static final GpsAutotestAntidup dao = new GpsAutotestAntidup().dao();
}
