package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsAutotestResult2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsAutotestResult2 extends BaseGpsAutotestResult2<GpsAutotestResult2> {
	public static final GpsAutotestResult2 dao = new GpsAutotestResult2().dao();
}
