package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsCartonboxtwentyResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsCartonboxtwentyResult extends BaseGpsCartonboxtwentyResult<GpsCartonboxtwentyResult> {
	public static final GpsCartonboxtwentyResult dao = new GpsCartonboxtwentyResult().dao();
}
