package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsCoupletestResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsCoupletestResult extends BaseGpsCoupletestResult<GpsCoupletestResult> {

	public static final GpsCoupletestResult dao = new GpsCoupletestResult().dao();
}
