package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsManusimdataparam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsManusimdataparam extends BaseGpsManusimdataparam<GpsManusimdataparam> {

	public static final GpsManusimdataparam dao = new GpsManusimdataparam().dao();
}
