package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsManuprintparam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsManuprintparam extends BaseGpsManuprintparam<GpsManuprintparam> {
	public static final GpsManuprintparam dao = new GpsManuprintparam().dao();
}
