package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsManucpparam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsManucpparam extends BaseGpsManucpparam<GpsManucpparam> {

	public static final GpsManucpparam dao = new GpsManucpparam().dao();
}
