package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseGpsTestresult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsTestresult extends BaseGpsTestresult<GpsTestresult> {
	public static final GpsTestresult dao = new GpsTestresult().dao();
}
