package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseLine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Line extends BaseLine<Line> {

	public static final Line dao = new Line().dao();
}
