package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseLineComputer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LineComputer extends BaseLineComputer<LineComputer> {
	public static final LineComputer dao = new LineComputer().dao();
}
