package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseLTestLogMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LTestLogMessage extends BaseLTestLogMessage<LTestLogMessage> {

	public static final LTestLogMessage dao = new LTestLogMessage().dao();
}
