package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseLUserAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LUserAccount extends BaseLUserAccount<LUserAccount> {
	public static final LUserAccount dao = new LUserAccount().dao();
}
