package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseModelCapacity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModelCapacity extends BaseModelCapacity<ModelCapacity> {
	public static final ModelCapacity dao = new ModelCapacity().dao();
}
