package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseModelCapacityStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModelCapacityStatus extends BaseModelCapacityStatus<ModelCapacityStatus> {
	public static final ModelCapacityStatus dao = new ModelCapacityStatus().dao();
}
