package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseNetMarkIMEI;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NetMarkIMEI extends BaseNetMarkIMEI<NetMarkIMEI> {
	public static final NetMarkIMEI dao = new NetMarkIMEI().dao();
}
