package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseOrderStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderStatus extends BaseOrderStatus<OrderStatus> {
	public static final OrderStatus dao = new OrderStatus().dao();
}
