package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseOrdersFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrdersFile extends BaseOrdersFile<OrdersFile> {
	public static final OrdersFile dao = new OrdersFile().dao();
}
