package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseOrderFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderFile extends BaseOrderFile<OrderFile> {

	public static final OrderFile dao = new OrderFile().dao();
}
