package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {

	public static final Orders dao = new Orders().dao();
}
