package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseOrderDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetails extends BaseOrderDetails<OrderDetails> {

	public static final OrderDetails dao = new OrderDetails().dao();
}
