package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseOrdersStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrdersStatus extends BaseOrdersStatus<OrdersStatus> {
	public static final OrdersStatus dao = new OrdersStatus().dao();
}
