package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Process extends BaseProcess<Process> {
	public static final Process dao = new Process().dao();
}
