package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseProcessGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProcessGroup extends BaseProcessGroup<ProcessGroup> {
	public static final ProcessGroup dao = new ProcessGroup().dao();
}
