package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseProductionActionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductionActionLog extends BaseProductionActionLog<ProductionActionLog> {
	public static final ProductionActionLog dao = new ProductionActionLog().dao();
}
