package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSchedulingPlanStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchedulingPlanStatus extends BaseSchedulingPlanStatus<SchedulingPlanStatus> {

	public static final SchedulingPlanStatus dao = new SchedulingPlanStatus().dao();
}
