package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSchedulingPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchedulingPlan extends BaseSchedulingPlan<SchedulingPlan> {
	public static final SchedulingPlan dao = new SchedulingPlan().dao();
}
