package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopCustomer extends BaseSopCustomer<SopCustomer> {
	public static final SopCustomer dao = new SopCustomer().dao();
}
