package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopCountLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopCountLog extends BaseSopCountLog<SopCountLog> {

	public static final SopCountLog dao = new SopCountLog().dao();
}
