package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopConfirmLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopConfirmLog extends BaseSopConfirmLog<SopConfirmLog> {
	public static final SopConfirmLog dao = new SopConfirmLog().dao();
}
