package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopFileHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopFileHistory extends BaseSopFileHistory<SopFileHistory> {
	public static final SopFileHistory dao = new SopFileHistory().dao();
}
