package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopFile extends BaseSopFile<SopFile> {
	public static final SopFile dao = new SopFile().dao();
}
