package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopFaceInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopFaceInformation extends BaseSopFaceInformation<SopFaceInformation> {
	public static final SopFaceInformation dao = new SopFaceInformation().dao();
}
