package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopFactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopFactory extends BaseSopFactory<SopFactory> {

	public static final SopFactory dao = new SopFactory().dao();
}
