package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopFilePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopFilePicture extends BaseSopFilePicture<SopFilePicture> {
	public static final SopFilePicture dao = new SopFilePicture().dao();
}
