package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopHistoryDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopHistoryDetail extends BaseSopHistoryDetail<SopHistoryDetail> {
	public static final SopHistoryDetail dao = new SopHistoryDetail().dao();
}
