package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopLoginLog extends BaseSopLoginLog<SopLoginLog> {

	public static final SopLoginLog dao = new SopLoginLog().dao();
}
