package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopNoticeHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopNoticeHistory extends BaseSopNoticeHistory<SopNoticeHistory> {
	public static final SopNoticeHistory dao = new SopNoticeHistory().dao();
}
