package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopPictureHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopPictureHistory extends BaseSopPictureHistory<SopPictureHistory> {
	public static final SopPictureHistory dao = new SopPictureHistory().dao();
}
