package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopProductModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopProductModel extends BaseSopProductModel<SopProductModel> {
	public static final SopProductModel dao = new SopProductModel().dao();
}
