package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopPositionAssignment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopPositionAssignment extends BaseSopPositionAssignment<SopPositionAssignment> {

	public static final SopPositionAssignment dao = new SopPositionAssignment().dao();
}
