package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopSite extends BaseSopSite<SopSite> {

	public static final SopSite dao = new SopSite().dao();
}
