package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopSeriesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopSeriesModel extends BaseSopSeriesModel<SopSeriesModel> {
	public static final SopSeriesModel dao = new SopSeriesModel().dao();
}
