package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopSiteDisplay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopSiteDisplay extends BaseSopSiteDisplay<SopSiteDisplay> {
	public static final SopSiteDisplay dao = new SopSiteDisplay().dao();
}
