package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseSopWorkshop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SopWorkshop extends BaseSopWorkshop<SopWorkshop> {

	public static final SopWorkshop dao = new SopWorkshop().dao();
}
