package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseTestSystemSettingFunc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestSystemSettingFunc extends BaseTestSystemSettingFunc<TestSystemSettingFunc> {
	public static final TestSystemSettingFunc dao = new TestSystemSettingFunc().dao();
}
