package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseTestSystemSettingLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestSystemSettingLog extends BaseTestSystemSettingLog<TestSystemSettingLog> {
	public static final TestSystemSettingLog dao = new TestSystemSettingLog().dao();
}
