package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseTestSystemSettingOqc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestSystemSettingOqc extends BaseTestSystemSettingOqc<TestSystemSettingOqc> {
	public static final TestSystemSettingOqc dao = new TestSystemSettingOqc().dao();
}
