package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseTestSystemSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestSystemSetting extends BaseTestSystemSetting<TestSystemSetting> {

	public static final TestSystemSetting dao = new TestSystemSetting().dao();
}
