package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseUserActionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserActionLog extends BaseUserActionLog<UserActionLog> {
	public static final UserActionLog dao = new UserActionLog().dao();
}
