package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseWebUserType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebUserType extends BaseWebUserType<WebUserType> {
	public static final WebUserType dao = new WebUserType().dao();
}
