package com.jimi.mes_server.model;

import com.jimi.mes_server.model.base.BaseWorkingSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkingSchedule extends BaseWorkingSchedule<WorkingSchedule> {
	public static final WorkingSchedule dao = new WorkingSchedule().dao();
}
