package com.jimi.mes_report.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWorkstationsUseTime<M extends BaseWorkstationsUseTime<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorkstationsOrdersId(java.lang.Integer workstationsOrdersId) {
		set("workstations_orders_id", workstationsOrdersId);
		return (M)this;
	}
	
	public java.lang.Integer getWorkstationsOrdersId() {
		return getInt("workstations_orders_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setTotalProduct(java.lang.Integer totalProduct) {
		set("total_product", totalProduct);
		return (M)this;
	}
	
	public java.lang.Integer getTotalProduct() {
		return getInt("total_product");
	}

	public M setActualUseTime(java.lang.String actualUseTime) {
		set("actual_use_time", actualUseTime);
		return (M)this;
	}
	
	public java.lang.String getActualUseTime() {
		return getStr("actual_use_time");
	}

	public M setAverageUseTime(java.lang.String averageUseTime) {
		set("average_use_time", averageUseTime);
		return (M)this;
	}
	
	public java.lang.String getAverageUseTime() {
		return getStr("average_use_time");
	}

	public M setMinUsedTime(java.lang.String minUsedTime) {
		set("min_used_time", minUsedTime);
		return (M)this;
	}
	
	public java.lang.String getMinUsedTime() {
		return getStr("min_used_time");
	}

}
