package com.jimi.mes_report.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWorkstationProduction<M extends BaseWorkstationProduction<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTimeType(java.lang.Integer timeType) {
		set("time_type", timeType);
		return (M)this;
	}
	
	public java.lang.Integer getTimeType() {
		return getInt("time_type");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setProduct(java.lang.Integer product) {
		set("product", product);
		return (M)this;
	}
	
	public java.lang.Integer getProduct() {
		return getInt("product");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
