package com.jimi.mes_report.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderProduction<M extends BaseOrderProduction<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTimeType(java.lang.Integer timeType) {
		set("time_type", timeType);
		return (M)this;
	}
	
	public java.lang.Integer getTimeType() {
		return getInt("time_type");
	}

	public M setPlanProduct(java.lang.Integer planProduct) {
		set("plan_product", planProduct);
		return (M)this;
	}
	
	public java.lang.Integer getPlanProduct() {
		return getInt("plan_product");
	}

	public M setActualProduct(java.lang.Integer actualProduct) {
		set("actual_product", actualProduct);
		return (M)this;
	}
	
	public java.lang.Integer getActualProduct() {
		return getInt("actual_product");
	}

	public M setHourlyPlanProduct(java.lang.Integer hourlyPlanProduct) {
		set("hourly_plan_product", hourlyPlanProduct);
		return (M)this;
	}
	
	public java.lang.Integer getHourlyPlanProduct() {
		return getInt("hourly_plan_product");
	}

	public M setHourlyActualProduct(java.lang.Integer hourlyActualProduct) {
		set("hourly_actual_product", hourlyActualProduct);
		return (M)this;
	}
	
	public java.lang.Integer getHourlyActualProduct() {
		return getInt("hourly_actual_product");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
