package com.jimi.mes_report.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}
	
	public java.lang.String getOrderNumber() {
		return getStr("order_number");
	}

	public M setSoftModel(java.lang.String softModel) {
		set("soft_model", softModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("soft_model");
	}

	public M setSoftVersion(java.lang.String softVersion) {
		set("soft_version", softVersion);
		return (M)this;
	}
	
	public java.lang.String getSoftVersion() {
		return getStr("soft_version");
	}

	public M setProductionNumber(java.lang.String productionNumber) {
		set("production_number", productionNumber);
		return (M)this;
	}
	
	public java.lang.String getProductionNumber() {
		return getStr("production_number");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCompletionRate(java.lang.String completionRate) {
		set("completion_rate", completionRate);
		return (M)this;
	}
	
	public java.lang.String getCompletionRate() {
		return getStr("completion_rate");
	}

	public M setPlanProduct(java.lang.Integer planProduct) {
		set("plan_product", planProduct);
		return (M)this;
	}
	
	public java.lang.Integer getPlanProduct() {
		return getInt("plan_product");
	}

	public M setActualProduct(java.lang.Integer actualProduct) {
		set("actual_product", actualProduct);
		return (M)this;
	}
	
	public java.lang.Integer getActualProduct() {
		return getInt("actual_product");
	}

	public M setDiffenrence(java.lang.Integer diffenrence) {
		set("diffenrence", diffenrence);
		return (M)this;
	}
	
	public java.lang.Integer getDiffenrence() {
		return getInt("diffenrence");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
