package com.jimi.mes_report.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWorkstationsOrders<M extends BaseWorkstationsOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}
	
	public java.lang.String getOrderNumber() {
		return getStr("order_number");
	}

	public M setSoftModel(java.lang.String softModel) {
		set("soft_model", softModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("soft_model");
	}

	public M setSoftVersion(java.lang.String softVersion) {
		set("soft_version", softVersion);
		return (M)this;
	}
	
	public java.lang.String getSoftVersion() {
		return getStr("soft_version");
	}

	public M setProductionNumber(java.lang.String productionNumber) {
		set("production_number", productionNumber);
		return (M)this;
	}
	
	public java.lang.String getProductionNumber() {
		return getStr("production_number");
	}

	public M setTotalUseTime(java.lang.String totalUseTime) {
		set("total_use_time", totalUseTime);
		return (M)this;
	}
	
	public java.lang.String getTotalUseTime() {
		return getStr("total_use_time");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
