package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopFile<M extends BaseSopFile<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFileNumber(java.lang.String fileNumber) {
		set("file_number", fileNumber);
		return (M)this;
	}
	
	public java.lang.String getFileNumber() {
		return getStr("file_number");
	}

	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public M setCustomer(java.lang.String customer) {
		set("customer", customer);
		return (M)this;
	}
	
	public java.lang.String getCustomer() {
		return getStr("customer");
	}

	public M setSeriesModel(java.lang.String seriesModel) {
		set("series_model", seriesModel);
		return (M)this;
	}
	
	public java.lang.String getSeriesModel() {
		return getStr("series_model");
	}

	public M setProductModel(java.lang.String productModel) {
		set("product_model", productModel);
		return (M)this;
	}
	
	public java.lang.String getProductModel() {
		return getStr("product_model");
	}

	public M setReviewer(java.lang.String reviewer) {
		set("reviewer", reviewer);
		return (M)this;
	}
	
	public java.lang.String getReviewer() {
		return getStr("reviewer");
	}

	public M setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
		return (M)this;
	}
	
	public java.util.Date getReviewTime() {
		return get("review_time");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public M setPath (java.lang.String path ) {
		set("path ", path );
		return (M)this;
	}
	
	public java.lang.String getPath () {
		return getStr("path ");
	}

}
