package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopSite<M extends BaseSopSite<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSiteNumber(java.lang.String siteNumber) {
		set("site_number", siteNumber);
		return (M)this;
	}
	
	public java.lang.String getSiteNumber() {
		return getStr("site_number");
	}

	public M setSiteName(java.lang.String siteName) {
		set("site_name", siteName);
		return (M)this;
	}
	
	public java.lang.String getSiteName() {
		return getStr("site_name");
	}

	public M setProcessOrder(java.lang.Integer processOrder) {
		set("process_order", processOrder);
		return (M)this;
	}
	
	public java.lang.Integer getProcessOrder() {
		return getInt("process_order");
	}

	public M setLineId(java.lang.Integer lineId) {
		set("line_id", lineId);
		return (M)this;
	}
	
	public java.lang.Integer getLineId() {
		return getInt("line_id");
	}

	public M setPlayTimes(java.lang.Integer playTimes) {
		set("play_times", playTimes);
		return (M)this;
	}
	
	public java.lang.Integer getPlayTimes() {
		return getInt("play_times");
	}

	public M setSwitchInterval(java.lang.Integer switchInterval) {
		set("switch_interval", switchInterval);
		return (M)this;
	}
	
	public java.lang.Integer getSwitchInterval() {
		return getInt("switch_interval");
	}

	public M setMac(java.lang.String mac) {
		set("mac", mac);
		return (M)this;
	}
	
	public java.lang.String getMac() {
		return getStr("mac");
	}

	public M setSecondMac(java.lang.String secondMac) {
		set("second_mac", secondMac);
		return (M)this;
	}
	
	public java.lang.String getSecondMac() {
		return getStr("second_mac");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

}
