package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDashboardForCustomer<M extends BaseDashboardForCustomer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setZhidan(java.lang.String zhidan) {
		set("zhidan", zhidan);
		return (M)this;
	}
	
	public java.lang.String getZhidan() {
		return getStr("zhidan");
	}

	public M setSoftModel(java.lang.String softModel) {
		set("soft_model", softModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("soft_model");
	}

	public M setPlanProduction(java.lang.Integer planProduction) {
		set("plan_production", planProduction);
		return (M)this;
	}
	
	public java.lang.Integer getPlanProduction() {
		return getInt("plan_production");
	}

	public M setActualProduction(java.lang.Integer actualProduction) {
		set("actual_production", actualProduction);
		return (M)this;
	}
	
	public java.lang.Integer getActualProduction() {
		return getInt("actual_production");
	}

	public M setCompletionRate(java.math.BigDecimal completionRate) {
		set("completion_rate", completionRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getCompletionRate() {
		return get("completion_rate");
	}

	public M setTestingRate(java.math.BigDecimal testingRate) {
		set("testing_rate", testingRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getTestingRate() {
		return get("testing_rate");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setLine(java.lang.Integer line) {
		set("line", line);
		return (M)this;
	}
	
	public java.lang.Integer getLine() {
		return getInt("line");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
