package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsManucpparam<M extends BaseGpsManucpparam<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setCPIP(java.lang.String CPIP) {
		set("CPIP", CPIP);
		return (M)this;
	}
	
	public java.lang.String getCPIP() {
		return getStr("CPIP");
	}

	public M setZhiDan(java.lang.String ZhiDan) {
		set("ZhiDan", ZhiDan);
		return (M)this;
	}
	
	public java.lang.String getZhiDan() {
		return getStr("ZhiDan");
	}

	public M setIMEI1(java.lang.String IMEI1) {
		set("IMEI1", IMEI1);
		return (M)this;
	}
	
	public java.lang.String getIMEI1() {
		return getStr("IMEI1");
	}

	public M setIMEI2(java.lang.String IMEI2) {
		set("IMEI2", IMEI2);
		return (M)this;
	}
	
	public java.lang.String getIMEI2() {
		return getStr("IMEI2");
	}

	public M setIMEI3(java.lang.String IMEI3) {
		set("IMEI3", IMEI3);
		return (M)this;
	}
	
	public java.lang.String getIMEI3() {
		return getStr("IMEI3");
	}

	public M setSECTIONNO1(java.lang.String SECTIONNO1) {
		set("SECTIONNO1", SECTIONNO1);
		return (M)this;
	}
	
	public java.lang.String getSECTIONNO1() {
		return getStr("SECTIONNO1");
	}

	public M setSECTIONNO2(java.lang.String SECTIONNO2) {
		set("SECTIONNO2", SECTIONNO2);
		return (M)this;
	}
	
	public java.lang.String getSECTIONNO2() {
		return getStr("SECTIONNO2");
	}

	public M setCPRESULT(java.lang.String CPRESULT) {
		set("CPRESULT", CPRESULT);
		return (M)this;
	}
	
	public java.lang.String getCPRESULT() {
		return getStr("CPRESULT");
	}

	public M setCPTIME(java.lang.String CPTIME) {
		set("CPTIME", CPTIME);
		return (M)this;
	}
	
	public java.lang.String getCPTIME() {
		return getStr("CPTIME");
	}

	public M setCPTYPE(java.lang.String CPTYPE) {
		set("CPTYPE", CPTYPE);
		return (M)this;
	}
	
	public java.lang.String getCPTYPE() {
		return getStr("CPTYPE");
	}

	public M setCPFalseCount(java.lang.Integer CPFalseCount) {
		set("CPFalseCount", CPFalseCount);
		return (M)this;
	}
	
	public java.lang.Integer getCPFalseCount() {
		return getInt("CPFalseCount");
	}

	public M setRECPTIME(java.lang.String RECPTIME) {
		set("RECPTIME", RECPTIME);
		return (M)this;
	}
	
	public java.lang.String getRECPTIME() {
		return getStr("RECPTIME");
	}

	public M setCPERROR(java.lang.String CPERROR) {
		set("CPERROR", CPERROR);
		return (M)this;
	}
	
	public java.lang.String getCPERROR() {
		return getStr("CPERROR");
	}

}
