package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthority<M extends BaseAuthority<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOperation(java.lang.String operation) {
		set("operation", operation);
		return (M)this;
	}
	
	public java.lang.String getOperation() {
		return getStr("operation");
	}

	public M setPage(java.lang.String page) {
		set("page", page);
		return (M)this;
	}
	
	public java.lang.String getPage() {
		return getStr("page");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public M setSystem(java.lang.String system) {
		set("system", system);
		return (M)this;
	}
	
	public java.lang.String getSystem() {
		return getStr("system");
	}

	public M setUrls(java.lang.String urls) {
		set("urls", urls);
		return (M)this;
	}
	
	public java.lang.String getUrls() {
		return getStr("urls");
	}

}
