package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTestSystemSettingLog<M extends BaseTestSystemSettingLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSettingType(java.lang.Integer settingType) {
		set("setting_type", settingType);
		return (M)this;
	}
	
	public java.lang.Integer getSettingType() {
		return getInt("setting_type");
	}

	public M setOperationType(java.lang.Integer operationType) {
		set("operation_type", operationType);
		return (M)this;
	}
	
	public java.lang.Integer getOperationType() {
		return getInt("operation_type");
	}

	public M setSoftVersion(java.lang.String softVersion) {
		set("soft_version", softVersion);
		return (M)this;
	}
	
	public java.lang.String getSoftVersion() {
		return getStr("soft_version");
	}

	public M setOrderName(java.lang.String orderName) {
		set("order_name", orderName);
		return (M)this;
	}
	
	public java.lang.String getOrderName() {
		return getStr("order_name");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setResult(java.lang.Boolean result) {
		set("result", result);
		return (M)this;
	}
	
	public java.lang.Boolean getResult() {
		return get("result");
	}

	public M setStation(java.lang.String station) {
		set("station", station);
		return (M)this;
	}
	
	public java.lang.String getStation() {
		return getStr("station");
	}

}
