package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataRelativeUnique<M extends BaseDataRelativeUnique<M>> extends Model<M> implements IBean {

	public M setDATA1(java.lang.String DATA1) {
		set("DATA1", DATA1);
		return (M)this;
	}
	
	public java.lang.String getDATA1() {
		return getStr("DATA1");
	}

	public M setDATA2(java.lang.String DATA2) {
		set("DATA2", DATA2);
		return (M)this;
	}
	
	public java.lang.String getDATA2() {
		return getStr("DATA2");
	}

	public M setDATA3(java.lang.String DATA3) {
		set("DATA3", DATA3);
		return (M)this;
	}
	
	public java.lang.String getDATA3() {
		return getStr("DATA3");
	}

	public M setDATA4(java.lang.String DATA4) {
		set("DATA4", DATA4);
		return (M)this;
	}
	
	public java.lang.String getDATA4() {
		return getStr("DATA4");
	}

	public M setDATA5(java.lang.String DATA5) {
		set("DATA5", DATA5);
		return (M)this;
	}
	
	public java.lang.String getDATA5() {
		return getStr("DATA5");
	}

	public M setDATA6(java.lang.String DATA6) {
		set("DATA6", DATA6);
		return (M)this;
	}
	
	public java.lang.String getDATA6() {
		return getStr("DATA6");
	}

	public M setDATA7(java.lang.String DATA7) {
		set("DATA7", DATA7);
		return (M)this;
	}
	
	public java.lang.String getDATA7() {
		return getStr("DATA7");
	}

	public M setDATA8(java.lang.String DATA8) {
		set("DATA8", DATA8);
		return (M)this;
	}
	
	public java.lang.String getDATA8() {
		return getStr("DATA8");
	}

	public M setDATA9(java.lang.String DATA9) {
		set("DATA9", DATA9);
		return (M)this;
	}
	
	public java.lang.String getDATA9() {
		return getStr("DATA9");
	}

	public M setDATA10(java.lang.String DATA10) {
		set("DATA10", DATA10);
		return (M)this;
	}
	
	public java.lang.String getDATA10() {
		return getStr("DATA10");
	}

	public M setDATA11(java.lang.String DATA11) {
		set("DATA11", DATA11);
		return (M)this;
	}
	
	public java.lang.String getDATA11() {
		return getStr("DATA11");
	}

	public M setDATA12(java.lang.String DATA12) {
		set("DATA12", DATA12);
		return (M)this;
	}
	
	public java.lang.String getDATA12() {
		return getStr("DATA12");
	}

	public M setZhiDan(java.lang.String ZhiDan) {
		set("ZhiDan", ZhiDan);
		return (M)this;
	}
	
	public java.lang.String getZhiDan() {
		return getStr("ZhiDan");
	}

	public M setTestTime(java.util.Date TestTime) {
		set("TestTime", TestTime);
		return (M)this;
	}
	
	public java.util.Date getTestTime() {
		return get("TestTime");
	}

}
