package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setZhidan(java.lang.String zhidan) {
		set("zhidan", zhidan);
		return (M)this;
	}
	
	public java.lang.String getZhidan() {
		return getStr("zhidan");
	}

	public M setAlias(java.lang.String alias) {
		set("alias", alias);
		return (M)this;
	}
	
	public java.lang.String getAlias() {
		return getStr("alias");
	}

	public M setSoftModel(java.lang.String softModel) {
		set("soft_model", softModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("soft_model");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public M setProductNo(java.lang.String productNo) {
		set("product_no", productNo);
		return (M)this;
	}
	
	public java.lang.String getProductNo() {
		return getStr("product_no");
	}

	public M setCustomerNumber(java.lang.String customerNumber) {
		set("customer_number", customerNumber);
		return (M)this;
	}
	
	public java.lang.String getCustomerNumber() {
		return getStr("customer_number");
	}

	public M setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
		return (M)this;
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public M setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
		return (M)this;
	}
	
	public java.util.Date getOrderDate() {
		return get("order_date");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public M setDeliveryDate(java.util.Date deliveryDate) {
		set("delivery_date", deliveryDate);
		return (M)this;
	}
	
	public java.util.Date getDeliveryDate() {
		return get("delivery_date");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public M setIsRework(java.lang.Boolean isRework) {
		set("is_rework", isRework);
		return (M)this;
	}
	
	public java.lang.Boolean getIsRework() {
		return get("is_rework");
	}

	public M setFactory(java.lang.Integer factory) {
		set("factory", factory);
		return (M)this;
	}
	
	public java.lang.Integer getFactory() {
		return getInt("factory");
	}

	public M setCustomerMaterialNo(java.lang.String customerMaterialNo) {
		set("customer_material_no", customerMaterialNo);
		return (M)this;
	}
	
	public java.lang.String getCustomerMaterialNo() {
		return getStr("customer_material_no");
	}

	public M setReworkZhidan(java.lang.String reworkZhidan) {
		set("rework_zhidan", reworkZhidan);
		return (M)this;
	}
	
	public java.lang.String getReworkZhidan() {
		return getStr("rework_zhidan");
	}

	public M setReworkQuantity(java.lang.Integer reworkQuantity) {
		set("rework_quantity", reworkQuantity);
		return (M)this;
	}
	
	public java.lang.Integer getReworkQuantity() {
		return getInt("rework_quantity");
	}

	public M setScheduledQuantity(java.lang.Integer scheduledQuantity) {
		set("scheduled_quantity", scheduledQuantity);
		return (M)this;
	}
	
	public java.lang.Integer getScheduledQuantity() {
		return getInt("scheduled_quantity");
	}

	public M setProducedQuantity(java.lang.Integer producedQuantity) {
		set("produced_quantity", producedQuantity);
		return (M)this;
	}
	
	public java.lang.Integer getProducedQuantity() {
		return getInt("produced_quantity");
	}

	public M setUnfinishedReason(java.lang.String unfinishedReason) {
		set("unfinished_reason", unfinishedReason);
		return (M)this;
	}
	
	public java.lang.String getUnfinishedReason() {
		return getStr("unfinished_reason");
	}

	public M setOrderCreator(java.lang.Integer orderCreator) {
		set("order_creator", orderCreator);
		return (M)this;
	}
	
	public java.lang.Integer getOrderCreator() {
		return getInt("order_creator");
	}

	public M setOrderCreateTime(java.util.Date orderCreateTime) {
		set("order_create_time", orderCreateTime);
		return (M)this;
	}
	
	public java.util.Date getOrderCreateTime() {
		return get("order_create_time");
	}

	public M setOrderModifier(java.lang.Integer orderModifier) {
		set("order_modifier", orderModifier);
		return (M)this;
	}
	
	public java.lang.Integer getOrderModifier() {
		return getInt("order_modifier");
	}

	public M setOrderModifyTime(java.util.Date orderModifyTime) {
		set("order_modify_time", orderModifyTime);
		return (M)this;
	}
	
	public java.util.Date getOrderModifyTime() {
		return get("order_modify_time");
	}

	public M setAbnormalEndPerson(java.lang.Integer abnormalEndPerson) {
		set("abnormal_end_person", abnormalEndPerson);
		return (M)this;
	}
	
	public java.lang.Integer getAbnormalEndPerson() {
		return getInt("abnormal_end_person");
	}

	public M setAbnormalEndTime(java.util.Date abnormalEndTime) {
		set("abnormal_end_time", abnormalEndTime);
		return (M)this;
	}
	
	public java.util.Date getAbnormalEndTime() {
		return get("abnormal_end_time");
	}

	public M setAbnormalEndReason(java.lang.String abnormalEndReason) {
		set("abnormal_end_reason", abnormalEndReason);
		return (M)this;
	}
	
	public java.lang.String getAbnormalEndReason() {
		return getStr("abnormal_end_reason");
	}

	public M setPc(java.lang.String pc) {
		set("pc", pc);
		return (M)this;
	}
	
	public java.lang.String getPc() {
		return getStr("pc");
	}

	public M setPcRemarks(java.lang.String pcRemarks) {
		set("pc_remarks", pcRemarks);
		return (M)this;
	}
	
	public java.lang.String getPcRemarks() {
		return getStr("pc_remarks");
	}

	public M setPcRemarksTime(java.util.Date pcRemarksTime) {
		set("pc_remarks_time", pcRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getPcRemarksTime() {
		return get("pc_remarks_time");
	}

	public M setPmc(java.lang.String pmc) {
		set("pmc", pmc);
		return (M)this;
	}
	
	public java.lang.String getPmc() {
		return getStr("pmc");
	}

	public M setPmcRemarks (java.lang.String pmcRemarks ) {
		set("pmc_remarks ", pmcRemarks );
		return (M)this;
	}
	
	public java.lang.String getPmcRemarks () {
		return getStr("pmc_remarks ");
	}

	public M setPmcRemarksTime(java.util.Date pmcRemarksTime) {
		set("pmc_remarks_time", pmcRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getPmcRemarksTime() {
		return get("pmc_remarks_time");
	}

	public M setEngineer(java.lang.String engineer) {
		set("engineer", engineer);
		return (M)this;
	}
	
	public java.lang.String getEngineer() {
		return getStr("engineer");
	}

	public M setEngineerRemarks(java.lang.String engineerRemarks) {
		set("engineer_remarks", engineerRemarks);
		return (M)this;
	}
	
	public java.lang.String getEngineerRemarks() {
		return getStr("engineer_remarks");
	}

	public M setEngineerRemarksTime(java.util.Date engineerRemarksTime) {
		set("engineer_remarks_time", engineerRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getEngineerRemarksTime() {
		return get("engineer_remarks_time");
	}

	public M setProducer(java.lang.String producer) {
		set("producer", producer);
		return (M)this;
	}
	
	public java.lang.String getProducer() {
		return getStr("producer");
	}

	public M setProducerRemarks(java.lang.String producerRemarks) {
		set("producer_remarks", producerRemarks);
		return (M)this;
	}
	
	public java.lang.String getProducerRemarks() {
		return getStr("producer_remarks");
	}

	public M setProducerRemarksTime(java.util.Date producerRemarksTime) {
		set("producer_remarks_time", producerRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getProducerRemarksTime() {
		return get("producer_remarks_time");
	}

	public M setQc(java.lang.String qc) {
		set("qc", qc);
		return (M)this;
	}
	
	public java.lang.String getQc() {
		return getStr("qc");
	}

	public M setQcRemarks(java.lang.String qcRemarks) {
		set("qc_remarks", qcRemarks);
		return (M)this;
	}
	
	public java.lang.String getQcRemarks() {
		return getStr("qc_remarks");
	}

	public M setQcRemarksTime(java.util.Date qcRemarksTime) {
		set("qc_remarks_time", qcRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getQcRemarksTime() {
		return get("qc_remarks_time");
	}

}
