package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseModelCapacity<M extends BaseModelCapacity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSoftModel(java.lang.String softModel) {
		set("soft_model", softModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("soft_model");
	}

	public M setCustomerModel(java.lang.String customerModel) {
		set("customer_model", customerModel);
		return (M)this;
	}
	
	public java.lang.String getCustomerModel() {
		return getStr("customer_model");
	}

	public M setProcessGroup(java.lang.Integer processGroup) {
		set("process_group", processGroup);
		return (M)this;
	}
	
	public java.lang.Integer getProcessGroup() {
		return getInt("process_group");
	}

	public M setProcess(java.lang.Integer process) {
		set("process", process);
		return (M)this;
	}
	
	public java.lang.Integer getProcess() {
		return getInt("process");
	}

	public M setProcessPeopleQuantity(java.lang.Integer processPeopleQuantity) {
		set("process_people_quantity", processPeopleQuantity);
		return (M)this;
	}
	
	public java.lang.Integer getProcessPeopleQuantity() {
		return getInt("process_people_quantity");
	}

	public M setCapacity(java.lang.Integer capacity) {
		set("capacity", capacity);
		return (M)this;
	}
	
	public java.lang.Integer getCapacity() {
		return getInt("capacity");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setPosition(java.lang.Integer position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.Integer getPosition() {
		return getInt("position");
	}

	public M setRhythm(java.math.BigDecimal rhythm) {
		set("rhythm", rhythm);
		return (M)this;
	}
	
	public java.math.BigDecimal getRhythm() {
		return get("rhythm");
	}

}
