package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseModelCapacityStatus<M extends BaseModelCapacityStatus<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStatusName(java.lang.String statusName) {
		set("status_name", statusName);
		return (M)this;
	}
	
	public java.lang.String getStatusName() {
		return getStr("status_name");
	}

}
