package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNetMarkIMEI<M extends BaseNetMarkIMEI<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setNetMark(java.lang.String NetMark) {
		set("NetMark", NetMark);
		return (M)this;
	}
	
	public java.lang.String getNetMark() {
		return getStr("NetMark");
	}

	public M setIMEI(java.lang.String IMEI) {
		set("IMEI", IMEI);
		return (M)this;
	}
	
	public java.lang.String getIMEI() {
		return getStr("IMEI");
	}

	public M setPrintCount(java.lang.Integer PrintCount) {
		set("PrintCount", PrintCount);
		return (M)this;
	}
	
	public java.lang.Integer getPrintCount() {
		return getInt("PrintCount");
	}

	public M setSN(java.lang.String SN) {
		set("SN", SN);
		return (M)this;
	}
	
	public java.lang.String getSN() {
		return getStr("SN");
	}

	public M setZhidan(java.lang.String Zhidan) {
		set("Zhidan", Zhidan);
		return (M)this;
	}
	
	public java.lang.String getZhidan() {
		return getStr("Zhidan");
	}

	public M setNMTime(java.util.Date NMTime) {
		set("NMTime", NMTime);
		return (M)this;
	}
	
	public java.util.Date getNMTime() {
		return get("NMTime");
	}

	public M setRFID(java.lang.String RFID) {
		set("RFID", RFID);
		return (M)this;
	}
	
	public java.lang.String getRFID() {
		return getStr("RFID");
	}

	public M setJsPrinttime(java.util.Date jsPrinttime) {
		set("JS_PrintTime", jsPrinttime);
		return (M)this;
	}
	
	public java.util.Date getJsPrinttime() {
		return get("JS_PrintTime");
	}

	public M setJsTemplate(java.lang.String jsTemplate) {
		set("JS_TemPlate", jsTemplate);
		return (M)this;
	}
	
	public java.lang.String getJsTemplate() {
		return getStr("JS_TemPlate");
	}

	public M setRePrintNum(java.lang.Integer RePrintNum) {
		set("RePrintNum", RePrintNum);
		return (M)this;
	}
	
	public java.lang.Integer getRePrintNum() {
		return getInt("RePrintNum");
	}

	public M setRePrintFirstTime(java.util.Date RePrintFirstTime) {
		set("RePrintFirstTime", RePrintFirstTime);
		return (M)this;
	}
	
	public java.util.Date getRePrintFirstTime() {
		return get("RePrintFirstTime");
	}

	public M setRePrintEndTime(java.util.Date RePrintEndTime) {
		set("RePrintEndTime", RePrintEndTime);
		return (M)this;
	}
	
	public java.util.Date getRePrintEndTime() {
		return get("RePrintEndTime");
	}

}
