package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopHistory<M extends BaseSopHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFileId(java.lang.Integer fileId) {
		set("file_id", fileId);
		return (M)this;
	}
	
	public java.lang.Integer getFileId() {
		return getInt("file_id");
	}

	public M setPushTime(java.util.Date pushTime) {
		set("push_time", pushTime);
		return (M)this;
	}
	
	public java.util.Date getPushTime() {
		return get("push_time");
	}

	public M setPushPersion(java.lang.String pushPersion) {
		set("push_persion", pushPersion);
		return (M)this;
	}
	
	public java.lang.String getPushPersion() {
		return getStr("push_persion");
	}

}
