package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopSiteDisplay<M extends BaseSopSiteDisplay<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSiteId(java.lang.Integer siteId) {
		set("site_id", siteId);
		return (M)this;
	}
	
	public java.lang.Integer getSiteId() {
		return getInt("site_id");
	}

	public M setPictures(java.lang.String pictures) {
		set("pictures", pictures);
		return (M)this;
	}
	
	public java.lang.String getPictures() {
		return getStr("pictures");
	}

	public M setNotices(java.lang.String notices) {
		set("notices", notices);
		return (M)this;
	}
	
	public java.lang.String getNotices() {
		return getStr("notices");
	}

	public M setFiles(java.lang.String files) {
		set("files", files);
		return (M)this;
	}
	
	public java.lang.String getFiles() {
		return getStr("files");
	}

}
