package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopPictureHistory<M extends BaseSopPictureHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSiteNumber(java.lang.String siteNumber) {
		set("site_number", siteNumber);
		return (M)this;
	}
	
	public java.lang.String getSiteNumber() {
		return getStr("site_number");
	}

	public M setSiteName(java.lang.String siteName) {
		set("site_name", siteName);
		return (M)this;
	}
	
	public java.lang.String getSiteName() {
		return getStr("site_name");
	}

	public M setLine(java.lang.String line) {
		set("line", line);
		return (M)this;
	}
	
	public java.lang.String getLine() {
		return getStr("line");
	}

	public M setWorkshop(java.lang.String workshop) {
		set("workshop", workshop);
		return (M)this;
	}
	
	public java.lang.String getWorkshop() {
		return getStr("workshop");
	}

	public M setFactory(java.lang.String factory) {
		set("factory", factory);
		return (M)this;
	}
	
	public java.lang.String getFactory() {
		return getStr("factory");
	}

	public M setPictureNumber(java.lang.String pictureNumber) {
		set("picture_number", pictureNumber);
		return (M)this;
	}
	
	public java.lang.String getPictureNumber() {
		return getStr("picture_number");
	}

	public M setPicturePath(java.lang.String picturePath) {
		set("picture_path", picturePath);
		return (M)this;
	}
	
	public java.lang.String getPicturePath() {
		return getStr("picture_path");
	}

	public M setFileHistoryId(java.lang.Integer fileHistoryId) {
		set("file_history_id", fileHistoryId);
		return (M)this;
	}
	
	public java.lang.Integer getFileHistoryId() {
		return getInt("file_history_id");
	}

	public M setPictureName(java.lang.String pictureName) {
		set("picture_name", pictureName);
		return (M)this;
	}
	
	public java.lang.String getPictureName() {
		return getStr("picture_name");
	}

}
