package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopProductModel<M extends BaseSopProductModel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProductModelName(java.lang.String productModelName) {
		set("product_model_name", productModelName);
		return (M)this;
	}
	
	public java.lang.String getProductModelName() {
		return getStr("product_model_name");
	}

	public M setSeriesModelId(java.lang.Integer seriesModelId) {
		set("series_model_id", seriesModelId);
		return (M)this;
	}
	
	public java.lang.Integer getSeriesModelId() {
		return getInt("series_model_id");
	}

}
