package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderDetails<M extends BaseOrderDetails<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrders(java.lang.Integer orders) {
		set("orders", orders);
		return (M)this;
	}
	
	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public M setOrderCreator(java.lang.Integer orderCreator) {
		set("order_creator", orderCreator);
		return (M)this;
	}
	
	public java.lang.Integer getOrderCreator() {
		return getInt("order_creator");
	}

	public M setOrderCreateTime(java.util.Date orderCreateTime) {
		set("order_create_time", orderCreateTime);
		return (M)this;
	}
	
	public java.util.Date getOrderCreateTime() {
		return get("order_create_time");
	}

	public M setOrderModifier(java.lang.Integer orderModifier) {
		set("order_modifier", orderModifier);
		return (M)this;
	}
	
	public java.lang.Integer getOrderModifier() {
		return getInt("order_modifier");
	}

	public M setOrderModifyTime(java.util.Date orderModifyTime) {
		set("order_modify_time", orderModifyTime);
		return (M)this;
	}
	
	public java.util.Date getOrderModifyTime() {
		return get("order_modify_time");
	}

	public M setDeletePerson(java.lang.Integer deletePerson) {
		set("delete_person", deletePerson);
		return (M)this;
	}
	
	public java.lang.Integer getDeletePerson() {
		return getInt("delete_person");
	}

	public M setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
		return (M)this;
	}
	
	public java.util.Date getDeleteTime() {
		return get("delete_time");
	}

	public M setDeleteReason(java.lang.String deleteReason) {
		set("delete_reason", deleteReason);
		return (M)this;
	}
	
	public java.lang.String getDeleteReason() {
		return getStr("delete_reason");
	}

	public M setAbnormalEndRemarks(java.lang.String abnormalEndRemarks) {
		set("abnormal_end_remarks", abnormalEndRemarks);
		return (M)this;
	}
	
	public java.lang.String getAbnormalEndRemarks() {
		return getStr("abnormal_end_remarks");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setPc(java.lang.Integer pc) {
		set("pc", pc);
		return (M)this;
	}
	
	public java.lang.Integer getPc() {
		return getInt("pc");
	}

	public M setPcRemarks(java.lang.String pcRemarks) {
		set("pc_remarks", pcRemarks);
		return (M)this;
	}
	
	public java.lang.String getPcRemarks() {
		return getStr("pc_remarks");
	}

	public M setPcRemarksTime(java.util.Date pcRemarksTime) {
		set("pc_remarks_time", pcRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getPcRemarksTime() {
		return get("pc_remarks_time");
	}

	public M setPmc(java.lang.Integer pmc) {
		set("pmc", pmc);
		return (M)this;
	}
	
	public java.lang.Integer getPmc() {
		return getInt("pmc");
	}

	public M setPmcRemarks (java.lang.String pmcRemarks ) {
		set("pmc_remarks ", pmcRemarks );
		return (M)this;
	}
	
	public java.lang.String getPmcRemarks () {
		return getStr("pmc_remarks ");
	}

	public M setPmcRemarksTime(java.util.Date pmcRemarksTime) {
		set("pmc_remarks_time", pmcRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getPmcRemarksTime() {
		return get("pmc_remarks_time");
	}

	public M setEngineer(java.lang.Integer engineer) {
		set("engineer", engineer);
		return (M)this;
	}
	
	public java.lang.Integer getEngineer() {
		return getInt("engineer");
	}

	public M setEngineerRemarks(java.lang.String engineerRemarks) {
		set("engineer_remarks", engineerRemarks);
		return (M)this;
	}
	
	public java.lang.String getEngineerRemarks() {
		return getStr("engineer_remarks");
	}

	public M setEngineerRemarksTime(java.util.Date engineerRemarksTime) {
		set("engineer_remarks_time", engineerRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getEngineerRemarksTime() {
		return get("engineer_remarks_time");
	}

	public M setProducer(java.lang.Integer producer) {
		set("producer", producer);
		return (M)this;
	}
	
	public java.lang.Integer getProducer() {
		return getInt("producer");
	}

	public M setProducerRemarks(java.lang.String producerRemarks) {
		set("producer_remarks", producerRemarks);
		return (M)this;
	}
	
	public java.lang.String getProducerRemarks() {
		return getStr("producer_remarks");
	}

	public M setProducerRemarksTime(java.util.Date producerRemarksTime) {
		set("producer_remarks_time", producerRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getProducerRemarksTime() {
		return get("producer_remarks_time");
	}

	public M setQc(java.lang.Integer qc) {
		set("qc", qc);
		return (M)this;
	}
	
	public java.lang.Integer getQc() {
		return getInt("qc");
	}

	public M setQcRemarks(java.lang.String qcRemarks) {
		set("qc_remarks", qcRemarks);
		return (M)this;
	}
	
	public java.lang.String getQcRemarks() {
		return getStr("qc_remarks");
	}

	public M setQcRemarksTime(java.util.Date qcRemarksTime) {
		set("qc_remarks_time", qcRemarksTime);
		return (M)this;
	}
	
	public java.util.Date getQcRemarksTime() {
		return get("qc_remarks_time");
	}

}
