package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTestSystemSetting<M extends BaseTestSystemSetting<M>> extends Model<M> implements IBean {

	public M setSoftWare(java.lang.String SoftWare) {
		set("SoftWare", SoftWare);
		return (M)this;
	}
	
	public java.lang.String getSoftWare() {
		return getStr("SoftWare");
	}

	public M setMachineName(java.lang.String MachineName) {
		set("MachineName", MachineName);
		return (M)this;
	}
	
	public java.lang.String getMachineName() {
		return getStr("MachineName");
	}

	public M setStation(java.lang.String Station) {
		set("Station", Station);
		return (M)this;
	}
	
	public java.lang.String getStation() {
		return getStr("Station");
	}

	public M setSetting0(java.lang.String Setting0) {
		set("Setting0", Setting0);
		return (M)this;
	}
	
	public java.lang.String getSetting0() {
		return getStr("Setting0");
	}

	public M setSetting1(java.lang.String Setting1) {
		set("Setting1", Setting1);
		return (M)this;
	}
	
	public java.lang.String getSetting1() {
		return getStr("Setting1");
	}

	public M setSetting2(java.lang.String Setting2) {
		set("Setting2", Setting2);
		return (M)this;
	}
	
	public java.lang.String getSetting2() {
		return getStr("Setting2");
	}

	public M setSetting3(java.lang.String Setting3) {
		set("Setting3", Setting3);
		return (M)this;
	}
	
	public java.lang.String getSetting3() {
		return getStr("Setting3");
	}

	public M setSetting4(java.lang.String Setting4) {
		set("Setting4", Setting4);
		return (M)this;
	}
	
	public java.lang.String getSetting4() {
		return getStr("Setting4");
	}

	public M setSetting5(java.lang.String Setting5) {
		set("Setting5", Setting5);
		return (M)this;
	}
	
	public java.lang.String getSetting5() {
		return getStr("Setting5");
	}

	public M setSetting6(java.lang.String Setting6) {
		set("Setting6", Setting6);
		return (M)this;
	}
	
	public java.lang.String getSetting6() {
		return getStr("Setting6");
	}

	public M setSetting7(java.lang.String Setting7) {
		set("Setting7", Setting7);
		return (M)this;
	}
	
	public java.lang.String getSetting7() {
		return getStr("Setting7");
	}

	public M setSetting8(java.lang.String Setting8) {
		set("Setting8", Setting8);
		return (M)this;
	}
	
	public java.lang.String getSetting8() {
		return getStr("Setting8");
	}

	public M setSetting9(java.lang.String Setting9) {
		set("Setting9", Setting9);
		return (M)this;
	}
	
	public java.lang.String getSetting9() {
		return getStr("Setting9");
	}

	public M setSetting10(java.lang.String Setting10) {
		set("Setting10", Setting10);
		return (M)this;
	}
	
	public java.lang.String getSetting10() {
		return getStr("Setting10");
	}

	public M setSetting11(java.lang.String Setting11) {
		set("Setting11", Setting11);
		return (M)this;
	}
	
	public java.lang.String getSetting11() {
		return getStr("Setting11");
	}

	public M setSetting12(java.lang.String Setting12) {
		set("Setting12", Setting12);
		return (M)this;
	}
	
	public java.lang.String getSetting12() {
		return getStr("Setting12");
	}

	public M setSetting13(java.lang.String Setting13) {
		set("Setting13", Setting13);
		return (M)this;
	}
	
	public java.lang.String getSetting13() {
		return getStr("Setting13");
	}

	public M setSetting14(java.lang.String Setting14) {
		set("Setting14", Setting14);
		return (M)this;
	}
	
	public java.lang.String getSetting14() {
		return getStr("Setting14");
	}

	public M setSetting15(java.lang.String Setting15) {
		set("Setting15", Setting15);
		return (M)this;
	}
	
	public java.lang.String getSetting15() {
		return getStr("Setting15");
	}

	public M setSetting16(java.lang.String Setting16) {
		set("Setting16", Setting16);
		return (M)this;
	}
	
	public java.lang.String getSetting16() {
		return getStr("Setting16");
	}

	public M setSetting17(java.lang.String Setting17) {
		set("Setting17", Setting17);
		return (M)this;
	}
	
	public java.lang.String getSetting17() {
		return getStr("Setting17");
	}

	public M setSetting18(java.lang.String Setting18) {
		set("Setting18", Setting18);
		return (M)this;
	}
	
	public java.lang.String getSetting18() {
		return getStr("Setting18");
	}

	public M setSetting19(java.lang.String Setting19) {
		set("Setting19", Setting19);
		return (M)this;
	}
	
	public java.lang.String getSetting19() {
		return getStr("Setting19");
	}

	public M setSetting20(java.lang.String Setting20) {
		set("Setting20", Setting20);
		return (M)this;
	}
	
	public java.lang.String getSetting20() {
		return getStr("Setting20");
	}

	public M setSetting21(java.lang.String Setting21) {
		set("Setting21", Setting21);
		return (M)this;
	}
	
	public java.lang.String getSetting21() {
		return getStr("Setting21");
	}

	public M setSetting22(java.lang.String Setting22) {
		set("Setting22", Setting22);
		return (M)this;
	}
	
	public java.lang.String getSetting22() {
		return getStr("Setting22");
	}

	public M setSetting23(java.lang.String Setting23) {
		set("Setting23", Setting23);
		return (M)this;
	}
	
	public java.lang.String getSetting23() {
		return getStr("Setting23");
	}

	public M setSetting24(java.lang.String Setting24) {
		set("Setting24", Setting24);
		return (M)this;
	}
	
	public java.lang.String getSetting24() {
		return getStr("Setting24");
	}

	public M setSetting25(java.lang.String Setting25) {
		set("Setting25", Setting25);
		return (M)this;
	}
	
	public java.lang.String getSetting25() {
		return getStr("Setting25");
	}

	public M setSetting26(java.lang.String Setting26) {
		set("Setting26", Setting26);
		return (M)this;
	}
	
	public java.lang.String getSetting26() {
		return getStr("Setting26");
	}

	public M setSetting27(java.lang.String Setting27) {
		set("Setting27", Setting27);
		return (M)this;
	}
	
	public java.lang.String getSetting27() {
		return getStr("Setting27");
	}

	public M setSetting28(java.lang.String Setting28) {
		set("Setting28", Setting28);
		return (M)this;
	}
	
	public java.lang.String getSetting28() {
		return getStr("Setting28");
	}

	public M setSetting29(java.lang.String Setting29) {
		set("Setting29", Setting29);
		return (M)this;
	}
	
	public java.lang.String getSetting29() {
		return getStr("Setting29");
	}

	public M setSetting30(java.lang.String Setting30) {
		set("Setting30", Setting30);
		return (M)this;
	}
	
	public java.lang.String getSetting30() {
		return getStr("Setting30");
	}

	public M setSetting31(java.lang.String Setting31) {
		set("Setting31", Setting31);
		return (M)this;
	}
	
	public java.lang.String getSetting31() {
		return getStr("Setting31");
	}

	public M setSetting32(java.lang.String Setting32) {
		set("Setting32", Setting32);
		return (M)this;
	}
	
	public java.lang.String getSetting32() {
		return getStr("Setting32");
	}

	public M setSetting33(java.lang.String Setting33) {
		set("Setting33", Setting33);
		return (M)this;
	}
	
	public java.lang.String getSetting33() {
		return getStr("Setting33");
	}

	public M setSetting34(java.lang.String Setting34) {
		set("Setting34", Setting34);
		return (M)this;
	}
	
	public java.lang.String getSetting34() {
		return getStr("Setting34");
	}

	public M setSetting35(java.lang.String Setting35) {
		set("Setting35", Setting35);
		return (M)this;
	}
	
	public java.lang.String getSetting35() {
		return getStr("Setting35");
	}

	public M setSetting36(java.lang.String Setting36) {
		set("Setting36", Setting36);
		return (M)this;
	}
	
	public java.lang.String getSetting36() {
		return getStr("Setting36");
	}

	public M setSetting37(java.lang.String Setting37) {
		set("Setting37", Setting37);
		return (M)this;
	}
	
	public java.lang.String getSetting37() {
		return getStr("Setting37");
	}

	public M setSetting38(java.lang.String Setting38) {
		set("Setting38", Setting38);
		return (M)this;
	}
	
	public java.lang.String getSetting38() {
		return getStr("Setting38");
	}

	public M setSetting39(java.lang.String Setting39) {
		set("Setting39", Setting39);
		return (M)this;
	}
	
	public java.lang.String getSetting39() {
		return getStr("Setting39");
	}

	public M setSetting40(java.lang.String Setting40) {
		set("Setting40", Setting40);
		return (M)this;
	}
	
	public java.lang.String getSetting40() {
		return getStr("Setting40");
	}

	public M setSetting41(java.lang.String Setting41) {
		set("Setting41", Setting41);
		return (M)this;
	}
	
	public java.lang.String getSetting41() {
		return getStr("Setting41");
	}

	public M setSetting42(java.lang.String Setting42) {
		set("Setting42", Setting42);
		return (M)this;
	}
	
	public java.lang.String getSetting42() {
		return getStr("Setting42");
	}

	public M setSetting43(java.lang.String Setting43) {
		set("Setting43", Setting43);
		return (M)this;
	}
	
	public java.lang.String getSetting43() {
		return getStr("Setting43");
	}

	public M setSetting44(java.lang.String Setting44) {
		set("Setting44", Setting44);
		return (M)this;
	}
	
	public java.lang.String getSetting44() {
		return getStr("Setting44");
	}

	public M setSetting45(java.lang.String Setting45) {
		set("Setting45", Setting45);
		return (M)this;
	}
	
	public java.lang.String getSetting45() {
		return getStr("Setting45");
	}

	public M setSetting46(java.lang.String Setting46) {
		set("Setting46", Setting46);
		return (M)this;
	}
	
	public java.lang.String getSetting46() {
		return getStr("Setting46");
	}

	public M setSetting47(java.lang.String Setting47) {
		set("Setting47", Setting47);
		return (M)this;
	}
	
	public java.lang.String getSetting47() {
		return getStr("Setting47");
	}

	public M setSetting48(java.lang.String Setting48) {
		set("Setting48", Setting48);
		return (M)this;
	}
	
	public java.lang.String getSetting48() {
		return getStr("Setting48");
	}

	public M setSetting49(java.lang.String Setting49) {
		set("Setting49", Setting49);
		return (M)this;
	}
	
	public java.lang.String getSetting49() {
		return getStr("Setting49");
	}

	public M setSetting50(java.lang.String Setting50) {
		set("Setting50", Setting50);
		return (M)this;
	}
	
	public java.lang.String getSetting50() {
		return getStr("Setting50");
	}

	public M setSetting51(java.lang.String Setting51) {
		set("Setting51", Setting51);
		return (M)this;
	}
	
	public java.lang.String getSetting51() {
		return getStr("Setting51");
	}

	public M setSetting52(java.lang.String Setting52) {
		set("Setting52", Setting52);
		return (M)this;
	}
	
	public java.lang.String getSetting52() {
		return getStr("Setting52");
	}

	public M setSetting53(java.lang.String Setting53) {
		set("Setting53", Setting53);
		return (M)this;
	}
	
	public java.lang.String getSetting53() {
		return getStr("Setting53");
	}

	public M setSetting54(java.lang.String Setting54) {
		set("Setting54", Setting54);
		return (M)this;
	}
	
	public java.lang.String getSetting54() {
		return getStr("Setting54");
	}

	public M setSetting55(java.lang.String Setting55) {
		set("Setting55", Setting55);
		return (M)this;
	}
	
	public java.lang.String getSetting55() {
		return getStr("Setting55");
	}

	public M setSetting56(java.lang.String Setting56) {
		set("Setting56", Setting56);
		return (M)this;
	}
	
	public java.lang.String getSetting56() {
		return getStr("Setting56");
	}

	public M setSetting57(java.lang.String Setting57) {
		set("Setting57", Setting57);
		return (M)this;
	}
	
	public java.lang.String getSetting57() {
		return getStr("Setting57");
	}

	public M setSetting58(java.lang.String Setting58) {
		set("Setting58", Setting58);
		return (M)this;
	}
	
	public java.lang.String getSetting58() {
		return getStr("Setting58");
	}

	public M setSetting59(java.lang.String Setting59) {
		set("Setting59", Setting59);
		return (M)this;
	}
	
	public java.lang.String getSetting59() {
		return getStr("Setting59");
	}

	public M setSetting60(java.lang.String Setting60) {
		set("Setting60", Setting60);
		return (M)this;
	}
	
	public java.lang.String getSetting60() {
		return getStr("Setting60");
	}

	public M setSetting61(java.lang.String Setting61) {
		set("Setting61", Setting61);
		return (M)this;
	}
	
	public java.lang.String getSetting61() {
		return getStr("Setting61");
	}

	public M setSetting62(java.lang.String Setting62) {
		set("Setting62", Setting62);
		return (M)this;
	}
	
	public java.lang.String getSetting62() {
		return getStr("Setting62");
	}

	public M setSetting63(java.lang.String Setting63) {
		set("Setting63", Setting63);
		return (M)this;
	}
	
	public java.lang.String getSetting63() {
		return getStr("Setting63");
	}

	public M setSetting64(java.lang.String Setting64) {
		set("Setting64", Setting64);
		return (M)this;
	}
	
	public java.lang.String getSetting64() {
		return getStr("Setting64");
	}

	public M setSetting65(java.lang.String Setting65) {
		set("Setting65", Setting65);
		return (M)this;
	}
	
	public java.lang.String getSetting65() {
		return getStr("Setting65");
	}

	public M setSetting66(java.lang.String Setting66) {
		set("Setting66", Setting66);
		return (M)this;
	}
	
	public java.lang.String getSetting66() {
		return getStr("Setting66");
	}

	public M setSetting67(java.lang.String Setting67) {
		set("Setting67", Setting67);
		return (M)this;
	}
	
	public java.lang.String getSetting67() {
		return getStr("Setting67");
	}

	public M setRecordTime(java.util.Date RecordTime) {
		set("RecordTime", RecordTime);
		return (M)this;
	}
	
	public java.util.Date getRecordTime() {
		return get("RecordTime");
	}

}
