package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopSeriesModel<M extends BaseSopSeriesModel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSeriesModelName(java.lang.String seriesModelName) {
		set("series_model_name", seriesModelName);
		return (M)this;
	}
	
	public java.lang.String getSeriesModelName() {
		return getStr("series_model_name");
	}

}
