package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsManusimdataparam<M extends BaseGpsManusimdataparam<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setSDIP(java.lang.String SDIP) {
		set("SDIP", SDIP);
		return (M)this;
	}
	
	public java.lang.String getSDIP() {
		return getStr("SDIP");
	}

	public M setRID(java.lang.String RID) {
		set("RID", RID);
		return (M)this;
	}
	
	public java.lang.String getRID() {
		return getStr("RID");
	}

	public M setIMEI(java.lang.String IMEI) {
		set("IMEI", IMEI);
		return (M)this;
	}
	
	public java.lang.String getIMEI() {
		return getStr("IMEI");
	}

	public M setCID(java.lang.String CID) {
		set("CID", CID);
		return (M)this;
	}
	
	public java.lang.String getCID() {
		return getStr("CID");
	}

	public M setICCID(java.lang.String ICCID) {
		set("ICCID", ICCID);
		return (M)this;
	}
	
	public java.lang.String getICCID() {
		return getStr("ICCID");
	}

	public M setSDOperator(java.lang.String SDOperator) {
		set("SDOperator", SDOperator);
		return (M)this;
	}
	
	public java.lang.String getSDOperator() {
		return getStr("SDOperator");
	}

	public M setSDTime(java.lang.String SDTime) {
		set("SDTime", SDTime);
		return (M)this;
	}
	
	public java.lang.String getSDTime() {
		return getStr("SDTime");
	}

	public M setSDRESULT(java.lang.Integer SDRESULT) {
		set("SDRESULT", SDRESULT);
		return (M)this;
	}
	
	public java.lang.Integer getSDRESULT() {
		return getInt("SDRESULT");
	}

	public M setReSDTime(java.lang.String ReSDTime) {
		set("ReSDTime", ReSDTime);
		return (M)this;
	}
	
	public java.lang.String getReSDTime() {
		return getStr("ReSDTime");
	}

	public M setReSDCount(java.lang.Integer ReSDCount) {
		set("ReSDCount", ReSDCount);
		return (M)this;
	}
	
	public java.lang.Integer getReSDCount() {
		return getInt("ReSDCount");
	}

	public M setTestTime(java.util.Date TestTime) {
		set("TestTime", TestTime);
		return (M)this;
	}
	
	public java.util.Date getTestTime() {
		return get("TestTime");
	}

}
