package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopPositionAssignment<M extends BaseSopPositionAssignment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLineId(java.lang.Integer lineId) {
		set("line_id", lineId);
		return (M)this;
	}
	
	public java.lang.Integer getLineId() {
		return getInt("line_id");
	}

	public M setSiteId(java.lang.Integer siteId) {
		set("site_id", siteId);
		return (M)this;
	}
	
	public java.lang.Integer getSiteId() {
		return getInt("site_id");
	}

	public M setProcessId(java.lang.Integer processId) {
		set("process_id", processId);
		return (M)this;
	}
	
	public java.lang.Integer getProcessId() {
		return getInt("process_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

}
