package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsCartonboxtwentyResult<M extends BaseGpsCartonboxtwentyResult<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setBoxNo(java.lang.String BoxNo) {
		set("BoxNo", BoxNo);
		return (M)this;
	}
	
	public java.lang.String getBoxNo() {
		return getStr("BoxNo");
	}

	public M setIMEI(java.lang.String IMEI) {
		set("IMEI", IMEI);
		return (M)this;
	}
	
	public java.lang.String getIMEI() {
		return getStr("IMEI");
	}

	public M setZhiDan(java.lang.String ZhiDan) {
		set("ZhiDan", ZhiDan);
		return (M)this;
	}
	
	public java.lang.String getZhiDan() {
		return getStr("ZhiDan");
	}

	public M setSoftModel(java.lang.String SoftModel) {
		set("SoftModel", SoftModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("SoftModel");
	}

	public M setVersion(java.lang.String Version) {
		set("Version", Version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("Version");
	}

	public M setProductCode(java.lang.String ProductCode) {
		set("ProductCode", ProductCode);
		return (M)this;
	}
	
	public java.lang.String getProductCode() {
		return getStr("ProductCode");
	}

	public M setColor(java.lang.String Color) {
		set("Color", Color);
		return (M)this;
	}
	
	public java.lang.String getColor() {
		return getStr("Color");
	}

	public M setQty(java.lang.String Qty) {
		set("Qty", Qty);
		return (M)this;
	}
	
	public java.lang.String getQty() {
		return getStr("Qty");
	}

	public M setWeight(java.lang.String Weight) {
		set("Weight", Weight);
		return (M)this;
	}
	
	public java.lang.String getWeight() {
		return getStr("Weight");
	}

	public M setDate(java.lang.String Date) {
		set("Date", Date);
		return (M)this;
	}
	
	public java.lang.String getDate() {
		return getStr("Date");
	}

	public M setTACInfo(java.lang.String TACInfo) {
		set("TACInfo", TACInfo);
		return (M)this;
	}
	
	public java.lang.String getTACInfo() {
		return getStr("TACInfo");
	}

	public M setCompanyName(java.lang.String CompanyName) {
		set("CompanyName", CompanyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("CompanyName");
	}

	public M setTesterId(java.lang.String TesterId) {
		set("TesterId", TesterId);
		return (M)this;
	}
	
	public java.lang.String getTesterId() {
		return getStr("TesterId");
	}

	public M setTestTime(java.util.Date TestTime) {
		set("TestTime", TestTime);
		return (M)this;
	}
	
	public java.util.Date getTestTime() {
		return get("TestTime");
	}

	public M setRemark1(java.lang.String Remark1) {
		set("Remark1", Remark1);
		return (M)this;
	}
	
	public java.lang.String getRemark1() {
		return getStr("Remark1");
	}

	public M setRemark2(java.lang.String Remark2) {
		set("Remark2", Remark2);
		return (M)this;
	}
	
	public java.lang.String getRemark2() {
		return getStr("Remark2");
	}

	public M setRemark3(java.lang.String Remark3) {
		set("Remark3", Remark3);
		return (M)this;
	}
	
	public java.lang.String getRemark3() {
		return getStr("Remark3");
	}

	public M setRemark4(java.lang.String Remark4) {
		set("Remark4", Remark4);
		return (M)this;
	}
	
	public java.lang.String getRemark4() {
		return getStr("Remark4");
	}

	public M setRemark5(java.lang.String Remark5) {
		set("Remark5", Remark5);
		return (M)this;
	}
	
	public java.lang.String getRemark5() {
		return getStr("Remark5");
	}

	public M setComputer(java.lang.String Computer) {
		set("Computer", Computer);
		return (M)this;
	}
	
	public java.lang.String getComputer() {
		return getStr("Computer");
	}

	public M setMaskFromV2(byte[] MaskFromV2) {
		set("_MASK_FROM_V2", MaskFromV2);
		return (M)this;
	}
	
	public byte[] getMaskFromV2() {
		return get("_MASK_FROM_V2");
	}

}
