package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCompany(java.lang.Integer company) {
		set("company", company);
		return (M)this;
	}
	
	public java.lang.Integer getCompany() {
		return getInt("company");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setNo(java.lang.String no) {
		set("no", no);
		return (M)this;
	}
	
	public java.lang.String getNo() {
		return getStr("no");
	}

	public M setIsEnabled(java.lang.Boolean isEnabled) {
		set("is_enabled", isEnabled);
		return (M)this;
	}
	
	public java.lang.Boolean getIsEnabled() {
		return get("is_enabled");
	}

}
