package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLine<M extends BaseLine<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLineNo(java.lang.String lineNo) {
		set("line_no", lineNo);
		return (M)this;
	}
	
	public java.lang.String getLineNo() {
		return getStr("line_no");
	}

	public M setLineName(java.lang.String lineName) {
		set("line_name", lineName);
		return (M)this;
	}
	
	public java.lang.String getLineName() {
		return getStr("line_name");
	}

	public M setLineRemark(java.lang.String lineRemark) {
		set("line_remark", lineRemark);
		return (M)this;
	}
	
	public java.lang.String getLineRemark() {
		return getStr("line_remark");
	}

	public M setLineDirector(java.lang.Integer lineDirector) {
		set("line_director", lineDirector);
		return (M)this;
	}
	
	public java.lang.Integer getLineDirector() {
		return getInt("line_director");
	}

	public M setProcessGroup(java.lang.Integer processGroup) {
		set("process_group", processGroup);
		return (M)this;
	}
	
	public java.lang.Integer getProcessGroup() {
		return getInt("process_group");
	}

}
