package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseModelCapacity<M extends BaseModelCapacity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSoftModel(java.lang.String softModel) {
		set("soft_model", softModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("soft_model");
	}

	public M setCustomerModel(java.lang.String customerModel) {
		set("customer_model", customerModel);
		return (M)this;
	}
	
	public java.lang.String getCustomerModel() {
		return getStr("customer_model");
	}

	public M setProcessGroup(java.lang.Integer processGroup) {
		set("process_group", processGroup);
		return (M)this;
	}
	
	public java.lang.Integer getProcessGroup() {
		return getInt("process_group");
	}

	public M setProcessPeopleQuantity(java.lang.Integer processPeopleQuantity) {
		set("process_people_quantity", processPeopleQuantity);
		return (M)this;
	}
	
	public java.lang.Integer getProcessPeopleQuantity() {
		return getInt("process_people_quantity");
	}

	public M setCapacity(java.lang.Integer capacity) {
		set("capacity", capacity);
		return (M)this;
	}
	
	public java.lang.Integer getCapacity() {
		return getInt("capacity");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setRhythm(java.math.BigDecimal rhythm) {
		set("rhythm", rhythm);
		return (M)this;
	}
	
	public java.math.BigDecimal getRhythm() {
		return get("rhythm");
	}

	public M setTransferLineTime(java.lang.Integer transferLineTime) {
		set("transfer_line_time", transferLineTime);
		return (M)this;
	}
	
	public java.lang.Integer getTransferLineTime() {
		return getInt("transfer_line_time");
	}

	public M setCustomerNumber(java.lang.String customerNumber) {
		set("customer_number", customerNumber);
		return (M)this;
	}
	
	public java.lang.String getCustomerNumber() {
		return getStr("customer_number");
	}

	public M setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
		return (M)this;
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public M setModelCapacityStatus(java.lang.Integer modelCapacityStatus) {
		set("model_capacity_status", modelCapacityStatus);
		return (M)this;
	}
	
	public java.lang.Integer getModelCapacityStatus() {
		return getInt("model_capacity_status");
	}

	public M setReviewRemark(java.lang.String reviewRemark) {
		set("review_remark", reviewRemark);
		return (M)this;
	}
	
	public java.lang.String getReviewRemark() {
		return getStr("review_remark");
	}

	public M setReviewer(java.lang.Integer reviewer) {
		set("reviewer", reviewer);
		return (M)this;
	}
	
	public java.lang.Integer getReviewer() {
		return getInt("reviewer");
	}

	public M setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
		return (M)this;
	}
	
	public java.util.Date getReviewTime() {
		return get("review_time");
	}

}
