package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopCustomer<M extends BaseSopCustomer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSopCustomer(java.lang.String sopCustomer) {
		set("sop_customer", sopCustomer);
		return (M)this;
	}
	
	public java.lang.String getSopCustomer() {
		return getStr("sop_customer");
	}

	public M setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
		return (M)this;
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public M setFactoryId(java.lang.Integer factoryId) {
		set("factory_id", factoryId);
		return (M)this;
	}
	
	public java.lang.Integer getFactoryId() {
		return getInt("factory_id");
	}

}
