package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSopFactory<M extends BaseSopFactory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFactoryAlias(java.lang.String factoryAlias) {
		set("factory_alias", factoryAlias);
		return (M)this;
	}
	
	public java.lang.String getFactoryAlias() {
		return getStr("factory_alias");
	}

	public M setAbbreviation(java.lang.String abbreviation) {
		set("abbreviation", abbreviation);
		return (M)this;
	}
	
	public java.lang.String getAbbreviation() {
		return getStr("abbreviation");
	}

	public M setFullName(java.lang.String fullName) {
		set("full_name", fullName);
		return (M)this;
	}
	
	public java.lang.String getFullName() {
		return getStr("full_name");
	}

}
