package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLTestLogMessage<M extends BaseLTestLogMessage<M>> extends Model<M> implements IBean {

	public M setSN(java.lang.String SN) {
		set("SN", SN);
		return (M)this;
	}
	
	public java.lang.String getSN() {
		return getStr("SN");
	}

	public M setIMEI(java.lang.String IMEI) {
		set("IMEI", IMEI);
		return (M)this;
	}
	
	public java.lang.String getIMEI() {
		return getStr("IMEI");
	}

	public M setSoftModel(java.lang.String SoftModel) {
		set("SoftModel", SoftModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("SoftModel");
	}

	public M setVersion(java.lang.String Version) {
		set("Version", Version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("Version");
	}

	public M setZhiDan(java.lang.String ZhiDan) {
		set("ZhiDan", ZhiDan);
		return (M)this;
	}
	
	public java.lang.String getZhiDan() {
		return getStr("ZhiDan");
	}

	public M setErrorMessage1(java.lang.String ErrorMessage1) {
		set("ErrorMessage1", ErrorMessage1);
		return (M)this;
	}
	
	public java.lang.String getErrorMessage1() {
		return getStr("ErrorMessage1");
	}

	public M setCategoryNum1(java.lang.String CategoryNum1) {
		set("CategoryNum1", CategoryNum1);
		return (M)this;
	}
	
	public java.lang.String getCategoryNum1() {
		return getStr("CategoryNum1");
	}

	public M setErrorMessage2(java.lang.String ErrorMessage2) {
		set("ErrorMessage2", ErrorMessage2);
		return (M)this;
	}
	
	public java.lang.String getErrorMessage2() {
		return getStr("ErrorMessage2");
	}

	public M setCategoryNum2(java.lang.String CategoryNum2) {
		set("CategoryNum2", CategoryNum2);
		return (M)this;
	}
	
	public java.lang.String getCategoryNum2() {
		return getStr("CategoryNum2");
	}

	public M setErrorMessage3(java.lang.String ErrorMessage3) {
		set("ErrorMessage3", ErrorMessage3);
		return (M)this;
	}
	
	public java.lang.String getErrorMessage3() {
		return getStr("ErrorMessage3");
	}

	public M setCategoryNum3(java.lang.String CategoryNum3) {
		set("CategoryNum3", CategoryNum3);
		return (M)this;
	}
	
	public java.lang.String getCategoryNum3() {
		return getStr("CategoryNum3");
	}

	public M setErrorMessage4(java.lang.String ErrorMessage4) {
		set("ErrorMessage4", ErrorMessage4);
		return (M)this;
	}
	
	public java.lang.String getErrorMessage4() {
		return getStr("ErrorMessage4");
	}

	public M setCategoryNum4(java.lang.String CategoryNum4) {
		set("CategoryNum4", CategoryNum4);
		return (M)this;
	}
	
	public java.lang.String getCategoryNum4() {
		return getStr("CategoryNum4");
	}

	public M setComputer(java.lang.String Computer) {
		set("Computer", Computer);
		return (M)this;
	}
	
	public java.lang.String getComputer() {
		return getStr("Computer");
	}

	public M setComputer2(java.lang.String Computer2) {
		set("Computer2", Computer2);
		return (M)this;
	}
	
	public java.lang.String getComputer2() {
		return getStr("Computer2");
	}

	public M setComputer3(java.lang.String Computer3) {
		set("Computer3", Computer3);
		return (M)this;
	}
	
	public java.lang.String getComputer3() {
		return getStr("Computer3");
	}

	public M setComputer4(java.lang.String Computer4) {
		set("Computer4", Computer4);
		return (M)this;
	}
	
	public java.lang.String getComputer4() {
		return getStr("Computer4");
	}

	public M setTestTime(java.util.Date TestTime) {
		set("TestTime", TestTime);
		return (M)this;
	}
	
	public java.util.Date getTestTime() {
		return get("TestTime");
	}

	public M setComputer5(java.lang.String Computer5) {
		set("Computer5", Computer5);
		return (M)this;
	}
	
	public java.lang.String getComputer5() {
		return getStr("Computer5");
	}

	public M setErrorMessage5(java.lang.String ErrorMessage5) {
		set("ErrorMessage5", ErrorMessage5);
		return (M)this;
	}
	
	public java.lang.String getErrorMessage5() {
		return getStr("ErrorMessage5");
	}

	public M setCategoryNum5(java.lang.String CategoryNum5) {
		set("CategoryNum5", CategoryNum5);
		return (M)this;
	}
	
	public java.lang.String getCategoryNum5() {
		return getStr("CategoryNum5");
	}

}
