package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGpsAutotestAntidup<M extends BaseGpsAutotestAntidup<M>> extends Model<M> implements IBean {

	public M setSN(java.lang.String SN) {
		set("SN", SN);
		return (M)this;
	}
	
	public java.lang.String getSN() {
		return getStr("SN");
	}

	public M setData1(java.lang.String Data1) {
		set("Data1", Data1);
		return (M)this;
	}
	
	public java.lang.String getData1() {
		return getStr("Data1");
	}

	public M setData2(java.lang.String Data2) {
		set("Data2", Data2);
		return (M)this;
	}
	
	public java.lang.String getData2() {
		return getStr("Data2");
	}

	public M setData3(java.lang.String Data3) {
		set("Data3", Data3);
		return (M)this;
	}
	
	public java.lang.String getData3() {
		return getStr("Data3");
	}

	public M setData4(java.lang.String Data4) {
		set("Data4", Data4);
		return (M)this;
	}
	
	public java.lang.String getData4() {
		return getStr("Data4");
	}

	public M setData5(java.lang.String Data5) {
		set("Data5", Data5);
		return (M)this;
	}
	
	public java.lang.String getData5() {
		return getStr("Data5");
	}

	public M setZhiDan(java.lang.String ZhiDan) {
		set("ZhiDan", ZhiDan);
		return (M)this;
	}
	
	public java.lang.String getZhiDan() {
		return getStr("ZhiDan");
	}

	public M setComputer(java.lang.String Computer) {
		set("Computer", Computer);
		return (M)this;
	}
	
	public java.lang.String getComputer() {
		return getStr("Computer");
	}

	public M setTestTime(java.util.Date TestTime) {
		set("TestTime", TestTime);
		return (M)this;
	}
	
	public java.util.Date getTestTime() {
		return get("TestTime");
	}

	public M setVersion(java.lang.String Version) {
		set("Version", Version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("Version");
	}

	public M setSoftModel(java.lang.String SoftModel) {
		set("SoftModel", SoftModel);
		return (M)this;
	}
	
	public java.lang.String getSoftModel() {
		return getStr("SoftModel");
	}

}
