package com.jimi.mes_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderFile<M extends BaseOrderFile<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrders(java.lang.Integer orders) {
		set("orders", orders);
		return (M)this;
	}
	
	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	public M setFileType(java.lang.Integer fileType) {
		set("file_type", fileType);
		return (M)this;
	}
	
	public java.lang.Integer getFileType() {
		return getInt("file_type");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setUploader(java.lang.Integer uploader) {
		set("uploader", uploader);
		return (M)this;
	}
	
	public java.lang.Integer getUploader() {
		return getInt("uploader");
	}

	public M setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
		return (M)this;
	}
	
	public java.util.Date getUploadTime() {
		return get("upload_time");
	}

	public M setIsNormal(java.lang.Boolean isNormal) {
		set("is_normal", isNormal);
		return (M)this;
	}
	
	public java.lang.Boolean getIsNormal() {
		return get("is_normal");
	}

	public M setConfirmPerson(java.lang.Integer confirmPerson) {
		set("confirm_person", confirmPerson);
		return (M)this;
	}
	
	public java.lang.Integer getConfirmPerson() {
		return getInt("confirm_person");
	}

	public M setConfirmTime(java.util.Date confirmTime) {
		set("confirm_time", confirmTime);
		return (M)this;
	}
	
	public java.util.Date getConfirmTime() {
		return get("confirm_time");
	}

	public M setDeletePerson(java.lang.Integer deletePerson) {
		set("delete_person", deletePerson);
		return (M)this;
	}
	
	public java.lang.Integer getDeletePerson() {
		return getInt("delete_person");
	}

	public M setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
		return (M)this;
	}
	
	public java.util.Date getDeleteTime() {
		return get("delete_time");
	}

	public M setDeleteReason(java.lang.String deleteReason) {
		set("delete_reason", deleteReason);
		return (M)this;
	}
	
	public java.lang.String getDeleteReason() {
		return getStr("delete_reason");
	}

}
